services:
  web:
    build: .
    container_name: app-web
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 django_end.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media

  db:
    image: mysql:8.0
    container_name: app-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata:
  staticfiles:
  media:
